// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Chat struct {
	ID        string
	Name      string
	UpdatedAt int64
}

type Message struct {
	ID        string
	ChatID    string
	Role      string
	Text      string
	CreatedAt int64
}
